name: tagger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.4
  path: ^1.8.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true